import merge from 'merge-descriptors';
import getBucketRequestPayment from './getBucketRequestPayment';
import putBucketRequestPayment from './putBucketRequestPayment';
import putBucketEncryption from './putBucketEncryption';
import getBucketEncryption from './getBucketEncryption';
import deleteBucketEncryption from './deleteBucketEncryption';
import getBucketTags from './getBucketTags';
import putBucketTags from './putBucketTags';
import deleteBucketTags from './deleteBucketTags';
import putBucket from './putBucket';
import getBucketWebsite from './getBucketWebsite';
import putBucketWebsite from './putBucketWebsite';
import deleteBucketWebsite from './deleteBucketWebsite';
import getBucketLifecycle from './getBucketLifecycle';
import putBucketLifecycle from './putBucketLifecycle';
import deleteBucketLifecycle from './deleteBucketLifecycle';
import getBucketPolicy from './getBucketPolicy';
import putBucketPolicy from './putBucketPolicy';
import deleteBucketPolicy from './deleteBucketPolicy';
import getBucketVersioning from './getBucketVersioning';
import putBucketVersioning from './putBucketVersioning';
import * as getBucketInventoryOps from './getBucketInventory';
import * as deleteBucketInventoryOps from './deleteBucketInventory';
import * as listBucketInventoryOps from './listBucketInventory';
import * as putBucketInventoryOps from './putBucketInventory';
import * as abortBucketWormOps from './abortBucketWorm';
import * as completeBucketWormOps from './completeBucketWorm';
import * as extendBucketWormOps from './extendBucketWorm';
import * as getBucketWormOps from './getBucketWorm';
import * as initiateBucketWormOps from './initiateBucketWorm';
import * as getBucketStatOps from './getBucketStat';

const proto: any = {};
export default proto;

merge(proto, getBucketRequestPayment);
merge(proto, putBucketRequestPayment);
merge(proto, putBucketEncryption);
merge(proto, getBucketEncryption);
merge(proto, deleteBucketEncryption);
merge(proto, getBucketTags);
merge(proto, putBucketTags);
merge(proto, deleteBucketTags);
merge(proto, putBucket);
merge(proto, getBucketWebsite);
merge(proto, putBucketWebsite);
merge(proto, deleteBucketWebsite);
merge(proto, getBucketLifecycle);
merge(proto, putBucketLifecycle);
merge(proto, deleteBucketLifecycle);
merge(proto, getBucketPolicy);
merge(proto, putBucketPolicy);
merge(proto, deleteBucketPolicy);
merge(proto, getBucketVersioning);
merge(proto, putBucketVersioning);
merge(proto, getBucketInventoryOps);
merge(proto, deleteBucketInventoryOps);
merge(proto, listBucketInventoryOps);
merge(proto, putBucketInventoryOps);
merge(proto, abortBucketWormOps);
merge(proto, completeBucketWormOps);
merge(proto, extendBucketWormOps);
merge(proto, getBucketWormOps);
merge(proto, initiateBucketWormOps);
merge(proto, getBucketStatOps);
