import merge from 'merge-descriptors';
import getSymlinkOps from './getSymlink';
import putSymlinkOps from './putSymlink';
import getObjectMetaOps from './getObjectMeta';
import copyObjectOps from './copyObject';
import calculatePostSignatureOps from './calculatePostSignature';
import getObjectTaggingOps from './getObjectTagging';
import putObjectTaggingOps from './putObjectTagging';
import deleteObjectTaggingOps from './deleteObjectTagging';
import getBucketVersionsOps from './getBucketVersions';
import deleteMultiOps from './deleteMulti';
import getACLOps from './getACL';
import putACLOps from './putACL';
import headOps from './head';
import deleteOps from './delete';
import getOps from './get';
import * as postAsyncFetchOps from './postAsyncFetch';
import * as getAsyncFetchOps from './getAsyncFetch';
import generateObjectUrlOps from './generateObjectUrl';
import getObjectUrlOps from './getObjectUrl';
import signatureUrlOps from './signatureUrl';
import asyncSignatureUrlOps from './asyncSignatureUrl';
import signatureUrlV4Ops from './signatureUrlV4';
import * as signPostObjectPolicyV4Ops from './signPostObjectPolicyV4';

const proto: any = {};
export default proto;

merge(proto, getSymlinkOps);
merge(proto, putSymlinkOps);
merge(proto, getObjectMetaOps);
merge(proto, copyObjectOps);
merge(proto, calculatePostSignatureOps);
merge(proto, getObjectTaggingOps);
merge(proto, putObjectTaggingOps);
merge(proto, deleteObjectTaggingOps);
merge(proto, getBucketVersionsOps);
merge(proto, deleteMultiOps);
merge(proto, getACLOps);
merge(proto, putACLOps);
merge(proto, headOps);
merge(proto, deleteOps);
merge(proto, getOps);
merge(proto, postAsyncFetchOps);
merge(proto, getAsyncFetchOps);
merge(proto, generateObjectUrlOps);
merge(proto, getObjectUrlOps);
merge(proto, signatureUrlOps);
merge(proto, asyncSignatureUrlOps);
merge(proto, signatureUrlV4Ops);
merge(proto, signPostObjectPolicyV4Ops);
